/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todoApp;

import controller.ProjectController;
import java.sql.Connection;
import java.util.Date;
import java.util.List;
import model.Project;
import util.ConnectionFactory;
//import java.util.List;

public class App {

    public static void main(String[] args) {
        
        
//        ProjectController projectController = new ProjectController();
//        
//        Project project = new Project();
//        project.setName("Projeto Teste");
//        project.setDescription("description");
//        project.setCreatedAt(new Date());
//        project.setUpdatedAt(new Date());
//        projectController.save(project);
        
        ProjectController projectController = new ProjectController();
        
        Project project = new Project();
        project.setId(10);
        project.setName("Novo nome do projeto");
        project.setDescription("description");
        project.setCreatedAt(new Date());
        project.setUpdatedAt(new Date());
        projectController.update(project);     
        
        List<Project> projects = projectController.getAll();
        System.out.println("Total de projetos = " + projects.size());
        
        projectController.removeById(10);
       
    }
          
}
